### ISSUE TITLE
Working with Visual Studio 2010 express edition.

### ISSUE THREAD

**Issue by harshitha-sid** [sriramkashyap/OglTutorial#1]
Sir,

I'm a VII Sem student of M.S.R.I.T, who attended all your lectures on the 5th unit of Computer Graphics.
I tried running your code in visual studio 2010 express edition by copying your modified codes (which you had provided later for vs express 2011). I followed the steps that you've provided.

I'm able to build solution, it says build succeeded but wen I run it, I get an output on the console output saying : "Unable to load shader file : basic.vs " ( basic.vs is just an example I gave, infact its not able to load any .ps or .vs file). 

I've placed the files the same way you've done in your example OpenGL.sln.

Kindly help me Sir.

**Comment by sriramkashyap** [comment]
Hi,

 You can try modifying the code to use absolute file paths for the shader program  names. 

Regards,
Sriram

-----Original Message-----

**Comment by harshitha-sid** [comment]
Thank you Sir. Its working fine after giving the absolute paths.
